In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\rurue\Downloads/lac.csv')

In [3]:
df.dtypes

Date_Rptd          object
DATE_OCC           object
TIME_OCC           object
AREA                int64
AREA_NAME          object
Rpt_Dist_No         int64
Crm_Cd              int64
Crm_Cd_Desc        object
Vict_Age            int64
Vict_Sex           object
Vict_Descent       object
Weapon_Used_Cd    float64
Weapon_Desc        object
Status_Desc        object
LAT               float64
LON               float64
crm_cat            object
total_crm           int64
year                int64
VAge_Grp           object
dtype: object

In [4]:
df.shape

(902222, 20)

In [5]:
df

,Date_Rptd,DATE_OCC,TIME_OCC,AREA,AREA_NAME,Rpt_Dist_No,Crm_Cd,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Used_Cd,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,year,VAge_Grp
0,2015-03-30,2015-03-22,02:00:00,19,Mission,1961,330,BURGLARY FROM VEHICLE,26,F,W,NaN,NO WEAPON,Invest Cont,34.2464,-118.4675,BTFV,1,2015,26-35
1,2015-05-06,2015-05-01,19:00:00,17,Devonshire,1785,350,"THEFT, PERSON",73,M,W,NaN,NO WEAPON,Invest Cont,34.2308,-118.5398,PERSONAL THEFT,1,2015,61-Above
2,2015-01-21,2015-01-21,14:15:00,20,Olympic,2055,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,H,102.0,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,2015,26-35
3,2015-03-31,2015-03-23,06:00:00,15,N Hollywood,1522,354,THEFT OF IDENTITY,40,M,H,NaN,NO WEAPON,Invest Cont,34.1936,-118.4166,OTHER CRIMES,1,2015,36-45
4,2016-01-27,2015-06-01,08:00:00,6,Hollywood,644,354,THEFT OF IDENTITY,50,F,H,NaN,NO WEAPON,Invest Cont,34.0962,-118.3452,OTHER CRIMES,1,2015,45-60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902217,2019-02-24,2019-02-23,22:20:00,9,Van Nuys,904,210,ROBBERY,30,F,W,107.0,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,2019,26-35
902218,2019-02-22,2019-02-22,08:40:00,5,Harbor,569,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,W,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,2019,13-18
902219,2019-08-15,2019-08-14,18:10:00,7,Wilshire,701,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),40,M,W,NaN,NO WEAPON,Invest Cont,34.0871,-118.3732,BTFV,1,2019,36-45
902220,2019-01-06,2019-01-06,21:00:00,20,Olympic,2029,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,B,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,2019,45-60
902221,2019-02-01,2019-02-01,16:15:00,8,West LA,852,330,BURGLARY FROM VEHICLE,33,F,W,NaN,NO WEAPON,Invest Cont,34.0420,-118.4531,BTFV,1,2019,26-35

In [6]:
len(df['AREA_NAME'].unique())

21

In [7]:
df[df['Vict_Descent'].isna()]

,Date_Rptd,DATE_OCC,TIME_OCC,AREA,AREA_NAME,Rpt_Dist_No,Crm_Cd,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Used_Cd,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,year,VAge_Grp
19829,2015-08-20,2015-08-20,22:00:00,20,Olympic,2034,410,"BURGLARY FROM VEHICLE, ATTEMPTED",55,NaN,NaN,500.0,UNKNOWN WEAPON/OTHER WEAPON,Invest Cont,34.0597,-118.3042,BTFV,1,2015,45-60
23066,2015-11-30,2015-11-29,23:00:00,17,Devonshire,1762,943,CRUELTY TO ANIMALS,52,NaN,NaN,NaN,NO WEAPON,Invest Cont,34.2488,-118.5767,OTHER CRIMES,1,2015,45-60
90767,2015-08-19,2015-08-04,18:00:00,10,West Valley,1044,510,VEHICLE - STOLEN,66,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.1749,-118.5308,MVT,1,2015,61-Above
94690,2015-04-19,2015-04-19,22:55:00,14,Pacific,1457,251,SHOTS FIRED AT INHABITED DWELLING,43,NaN,NaN,102.0,HAND GUN,Invest Cont,33.9953,-118.4149,AGG. ASSAULTS,2,2015,36-45
101351,2015-01-04,2015-01-04,13:15:00,16,Foothill,1684,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,53,F,NaN,511.0,VERBAL THREAT,Adult Other,34.2166,-118.3919,SIMPLE ASSAULT,1,2015,45-60
106799,2015-11-11,2015-11-11,02:30:00,13,Newton,1313,520,VEHICLE - ATTEMPT STOLEN,70,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0267,-118.2528,MVT,2,2015,61-Above
109844,2015-09-17,2015-09-16,19:05:00,2,Rampart,285,210,ROBBERY,64,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Arrest,34.0477,-118.2751,ROBBERY,1,2015,61-Above
116477,2015-08-13,2015-08-12,13:00:00,7,Wilshire,738,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",24,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0621,-118.3385,OTHER THEFT,1,2015,19-25
133603,2015-07-14,2015-07-12,14:00:00,6,Hollywood,669,510,VEHICLE - STOLEN,24,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0949,-118.3092,MVT,1,2015,19-25
152051,2015-03-14,2015-03-14,10:00:00,15,N Hollywood,1543,421,THEFT FROM MOTOR VEHICLE - ATTEMPT,27,F,NaN,NaN,NO WEAPON,Adult Arrest,34.1667,-118.3992,BTFV,1,2015,26-35
158974,2015-09-27,2015-09-27,09:25:00,6,Hollywood,663,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",43,F,NaN,500.0,UNKNOWN WEAPON/OTHER WEAPON,Adult Arrest,34.0907,-118.3384,VANDALISM,1,2015,36-45
168825,2016-06-29,2015-02-10,12:00:00,7,Wilshire,721,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",52,NaN,NaN,NaN,NO WEAPON,Adult Other,34.0753,-118.3887,OTHER THEFT,1,2015,45-60
170763,2015-01-19,2015-01-19,23:20:00,18,Southeast,1844,943,CRUELTY TO ANIMALS,50,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Arrest,33.9373,-118.2608,OTHER CRIMES,1,2015,45-60
191971,2016-10-16,2016-10-16,16:55:00,14,Pacific,1494,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),68,M,NaN,NaN,NO WEAPON,Adult Other,33.9432,-118.4013,VANDALISM,1,2016,61-Above
210953,2016-07-20,2016-07-20,12:00:00,19,Mission,1915,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),28,NaN,NaN,NaN,NO WEAPON,Invest Cont,34.3021,-118.4467,BTFV,1,2016,26-35
301893,2016-07-20,2016-07-20,19:00:00,3,Southwest,362,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",69,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0168,-118.3491,VANDALISM,1,2016,61-Above
311009,2016-03-15,2016-03-15,06:19:00,18,Southeast,1862,231,ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER,24,NaN,NaN,102.0,HAND GUN,Adult Arrest,33.9301,-118.2782,AGG. ASSAULTS,1,2016,19-25
317344,2016-05-03,2016-05-02,20:00:00,20,Olympic,2027,330,BURGLARY FROM VEHICLE,28,F,NaN,NaN,NO WEAPON,Invest Cont,34.0636,-118.2966,BTFV,1,2016,26-35
324372,2016-10-02,2016-10-02,19:30:00,3,Southwest,362,210,ROBBERY,52,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0175,-118.3460,ROBBERY,1,2016,45-60
326823,2016-08-08,2016-08-07,08:00:00,7,Wilshire,743,943,CRUELTY TO ANIMALS,38,NaN,NaN,NaN,NO WEAPON,Invest Cont,34.0574,-118.3535,OTHER CRIMES,1,2016,36-45
412191,2017-03-23,2017-03-23,01:45:00,15,N Hollywood,1505,220,ATTEMPTED ROBBERY,37,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.2067,-118.3878,ROBBERY,1,2017,36-45
422715,2017-11-30,2017-11-30,21:11:00,3,Southwest,328,624,BATTERY - SIMPLE ASSAULT,31,F,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0268,-118.2808,SIMPLE ASSAULT,1,2017,26-35
433980,2017-05-02,2017-05-02,03:25:00,7,Wilshire,701,310,BURGLARY,50,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0835,-118.3734,BURGLARY,2,2017,45-60
439651,2017-12-09,2017-12-08,23:00:00,7,Wilshire,755,310,BURGLARY,29,M,NaN,NaN,NO WEAPON,Invest Cont,34.0504,-118.3532,BURGLARY,1,2017,26-35
445128,2017-01-24,2017-01-08,23:00:00,16,Foothill,1612,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,69,NaN,NaN,500.0,UNKNOWN WEAPON/OTHER WEAPON,Adult Arrest,34.2734,-118.4212,AGG. ASSAULTS,1,2017,61-Above
470265,2017-03-25,2017-03-25,20:32:00,1,Central,162,220,ATTEMPTED ROBBERY,27,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Arrest,34.0480,-118.2577,ROBBERY,1,2017,26-35
494414,2017-06-21,2017-06-16,19:20:00,6,Hollywood,642,900,VIOLATION OF COURT ORDER,21,NaN,NaN,NaN,NO WEAPON,Adult Other,34.0981,-118.3577,OTHER CRIMES,1,2017,19-25
515536,2017-03-28,2017-03-28,17:00:00,12,77th Street,1268,250,"SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT",20,NaN,NaN,106.0,UNKNOWN FIREARM,Juv Arrest,33.9640,-118.2739,AGG. ASSAULTS,1,2017,19-25
554668,2018-10-25,2018-10-24,22:00:00,3,Southwest,362,330,BURGLARY FROM VEHICLE,42,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0170,-118.3477,BTFV,2,2018,36-45
561126,2018-06-18,2018-04-02,12:00:00,13,Newton,1351,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),19,NaN,NaN,NaN,NO WEAPON,Invest Cont,34.0074,-118.2805,BTFV,1,2018,19-25
570655,2018-05-23,2018-05-23,01:00:00,10,West Valley,1075,510,VEHICLE - STOLEN,44,M,NaN,NaN,NO WEAPON,Invest Cont,34.1645,-118.5244,MVT,1,2018,36-45
576914,2018-05-07,2018-05-04,16:00:00,21,Topanga,2189,310,BURGLARY,54,M,NaN,NaN,NO WEAPON,Invest Cont,34.1695,-118.5749,BURGLARY,2,2018,45-60
578871,2018-06-22,2018-06-22,23:00:00,8,West LA,892,624,BATTERY - SIMPLE ASSAULT,33,NaN,NaN,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0340,-118.4404,SIMPLE ASSAULT,1,2018,26-35
582865,2018-03-05,2018-03-04,20:19:00,3,Southwest,312,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),17,NaN,NaN,NaN,NO WEAPON,Invest Cont,34.0289,-118.3563,VANDALISM,1,2018,13-18
613130,2018-03-21,2018-03-21,05:00:00,1,Central,153,330,BURGLARY FROM VEHICLE,118,NaN,NaN,NaN,NO WEAPON,Adult Arrest,34.0488,-118.2518,BTFV,1,2018,61-Above
653428,2018-10-29,2018-10-29,00:01:00,12,77th Street,1241,251,SHOTS FIRED AT INHABITED DWELLING,23,NaN,NaN,109.0,SEMI-AUTOMATIC PISTOL,Invest Cont,33.9846,-118.3279,AGG. ASSAULTS,1,2018,19-25
655119,2018-07-08,2018-07-07,21:00:00,5,Harbor,557,310,BURGLARY,43,NaN,NaN,NaN,NO WEAPON,Adult Arrest,33.7415,-118.2945,BURGLARY,1,2018,36-45
658418,2018-12-15,2018-12-15,01:15:00,8,West LA,858,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",19,NaN,NaN,101.0,REVOLVER,Invest Cont,34.0550,-118.3837,AGG. ASSAULTS,1,2018,19-25
666400,2018-12-07,2018-12-01,09:00:00,12,77th Street,1232,943,CRUELTY TO ANIMALS,21,NaN,NaN,106.0,UNKNOWN FIREARM,Invest Cont,33.9863,-118.3296,OTHER CRIMES,1,2018,19-25
676715,2018-05-02,2018-04-28,09:00:00,4,Hollenbeck,412,510,VEHICLE - STOLEN,19,M,NaN,NaN,NO WEAPON,Adult Arrest,34.0819,-118.2204,MVT,1,2018,19-25
684578,2018-05-06,2018-05-05,23:50:00,15,N Hollywood,1521,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),22,F,NaN,NaN,NO WEAPON,Adult Arrest,34.1958,-118.4181,VANDALISM,1,2018,19-25
691944,2018-06-03,2018-06-03,19:15:00,1,Central,101,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",34,NaN,NaN,201.0,KNIFE WITH BLADE OVER 6 INCHES IN LENGTH,Adult Arrest,34.0698,-118.2475,AGG. ASSAULTS,2,2018,26-35
698080,2019-01-18,2018-01-17,08:30:00,15,N Hollywood,1526,310,BURGLARY,35,F,NaN,NaN,NO WEAPON,Invest Cont,34.1886,-118.3812,BURGLARY,2,2018,26-35
836559,2019-10-01,2019-09-30,18:40:00,14,Pacific,1412,310,BURGLARY,62,NaN,NaN,500.0,UNKNOWN WEAPON/OTHER WEAPON,Adult Arrest,33.9933,-118.4765,BURGLARY,2,2019,61-Above
858673,2019-11-24,2019-11-24,10:30:00,12,77th Street,1241,943,CRUELTY TO ANIMALS,57,NaN,NaN,NaN,NO WEAPON,Invest Cont,33.9806,-118.3309,OTHER CRIMES,1,2019,45-60
900140,2019-02-16,2019-02-16,09:40:00,18,Southeast,1801,943,CRUELTY TO ANIMALS,32,NaN,NaN,308.0,STICK,Adult Arrest,33.9580,-118.2915,OTHER CRIMES,1,2019,26-35

In [8]:
df['VAge_Grp'].unique()

array(['26-35', '61-Above', '36-45', '45-60', '13-18', '19-25', '0-12'],
      dtype=object)

In [9]:
df

,Date_Rptd,DATE_OCC,TIME_OCC,AREA,AREA_NAME,Rpt_Dist_No,Crm_Cd,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Used_Cd,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,year,VAge_Grp
0,2015-03-30,2015-03-22,02:00:00,19,Mission,1961,330,BURGLARY FROM VEHICLE,26,F,W,NaN,NO WEAPON,Invest Cont,34.2464,-118.4675,BTFV,1,2015,26-35
1,2015-05-06,2015-05-01,19:00:00,17,Devonshire,1785,350,"THEFT, PERSON",73,M,W,NaN,NO WEAPON,Invest Cont,34.2308,-118.5398,PERSONAL THEFT,1,2015,61-Above
2,2015-01-21,2015-01-21,14:15:00,20,Olympic,2055,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,H,102.0,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,2015,26-35
3,2015-03-31,2015-03-23,06:00:00,15,N Hollywood,1522,354,THEFT OF IDENTITY,40,M,H,NaN,NO WEAPON,Invest Cont,34.1936,-118.4166,OTHER CRIMES,1,2015,36-45
4,2016-01-27,2015-06-01,08:00:00,6,Hollywood,644,354,THEFT OF IDENTITY,50,F,H,NaN,NO WEAPON,Invest Cont,34.0962,-118.3452,OTHER CRIMES,1,2015,45-60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902217,2019-02-24,2019-02-23,22:20:00,9,Van Nuys,904,210,ROBBERY,30,F,W,107.0,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,2019,26-35
902218,2019-02-22,2019-02-22,08:40:00,5,Harbor,569,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,W,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,2019,13-18
902219,2019-08-15,2019-08-14,18:10:00,7,Wilshire,701,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),40,M,W,NaN,NO WEAPON,Invest Cont,34.0871,-118.3732,BTFV,1,2019,36-45
902220,2019-01-06,2019-01-06,21:00:00,20,Olympic,2029,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,B,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,2019,45-60
902221,2019-02-01,2019-02-01,16:15:00,8,West LA,852,330,BURGLARY FROM VEHICLE,33,F,W,NaN,NO WEAPON,Invest Cont,34.0420,-118.4531,BTFV,1,2019,26-35

In [10]:
df.isna().sum()

Date_Rptd              0
DATE_OCC               0
TIME_OCC               0
AREA                   0
AREA_NAME              0
Rpt_Dist_No            0
Crm_Cd                 0
Crm_Cd_Desc            0
Vict_Age               0
Vict_Sex              34
Vict_Descent          46
Weapon_Used_Cd    545617
Weapon_Desc            0
Status_Desc            0
LAT                    0
LON                    0
crm_cat                0
total_crm              0
year                   0
VAge_Grp               0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
df

,Date_Rptd,DATE_OCC,TIME_OCC,AREA,AREA_NAME,Rpt_Dist_No,Crm_Cd,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Used_Cd,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,year,VAge_Grp
2,2015-01-21,2015-01-21,14:15:00,20,Olympic,2055,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,H,102.0,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,2015,26-35
8,2015-07-28,2015-07-28,10:20:00,12,77th Street,1251,210,ROBBERY,52,F,B,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,33.9757,-118.3294,ROBBERY,1,2015,45-60
9,2015-11-04,2015-11-03,21:00:00,4,Hollenbeck,443,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,75,F,H,511.0,VERBAL THREAT,Adult Other,34.0567,-118.2024,SIMPLE ASSAULT,1,2015,61-Above
10,2015-07-08,2015-07-08,22:00:00,2,Rampart,201,626,INTIMATE PARTNER - SIMPLE ASSAULT,31,F,H,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0891,-118.2992,SIMPLE ASSAULT,1,2015,26-35
13,2015-03-30,2015-03-30,04:30:00,18,Southeast,1821,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,26,F,B,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.9479,-118.2869,AGG. ASSAULTS,1,2015,26-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902215,2019-11-20,2019-11-20,18:50:00,3,Southwest,354,624,BATTERY - SIMPLE ASSAULT,27,M,H,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0196,-118.3237,SIMPLE ASSAULT,1,2019,26-35
902216,2019-01-20,2019-01-20,20:00:00,18,Southeast,1846,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,18,F,B,511.0,VERBAL THREAT,Invest Cont,33.9348,-118.2500,SIMPLE ASSAULT,2,2019,13-18
902217,2019-02-24,2019-02-23,22:20:00,9,Van Nuys,904,210,ROBBERY,30,F,W,107.0,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,2019,26-35
902218,2019-02-22,2019-02-22,08:40:00,5,Harbor,569,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,W,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,2019,13-18
902220,2019-01-06,2019-01-06,21:00:00,20,Olympic,2029,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,B,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,2019,45-60

In [13]:
cols = ['DATE_OCC', 'TIME_OCC', 'AREA_NAME', 'Crm_Cd_Desc', 'Vict_Age', 'Vict_Sex', 'Vict_Descent', 'Weapon_Desc', 'Status_Desc', 'LAT', 'LON', 'crm_cat', 'total_crm', 'VAge_Grp', 'year']

In [14]:
df = df.loc[:, cols]

In [15]:
def change_vict_desc(x):
    if x == 'A':
        return 'Other Asian'
    elif x == 'B':
        return 'Black'
    elif x == 'C':
        return 'Chinese'    
    elif x == 'D':
        return 'Cambodian'    
    elif x == 'F':
        return 'Filipino'
    elif x == 'G':
        return 'Guamanian'
    elif x == 'H':
        return 'Hispanic/Latin/Mexican'
    elif x == 'I':
        return 'American Indian/Alaskan Native'
    elif x == 'J':
        return 'Japanese'
    elif x == 'K':
        return 'Korean'
    elif x == 'L':
        return 'Laotian'
    elif x == 'O':
        return 'Other'
    elif x == 'p':
        return 'Pacific Islander'
    elif x == 'S':
        return 'Samoan'
    elif x == 'U':
        return 'Hawaiian'
    elif x == 'V':
        return 'Vietnamese'
    elif x == 'W':
        return 'White'
    elif x == 'X':
        return 'Unknown'
    elif x == 'Z':
        return 'Asian Indian'
    else:
        return 'Unknown'

In [16]:
df['Vict_Descent'] = df['Vict_Descent'].apply(change_vict_desc)

In [17]:
df

,DATE_OCC,TIME_OCC,AREA_NAME,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,VAge_Grp,year
2,2015-01-21,14:15:00,Olympic,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,Hispanic/Latin/Mexican,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,26-35,2015
8,2015-07-28,10:20:00,77th Street,ROBBERY,52,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,33.9757,-118.3294,ROBBERY,1,45-60,2015
9,2015-11-03,21:00:00,Hollenbeck,CRIMINAL THREATS - NO WEAPON DISPLAYED,75,F,Hispanic/Latin/Mexican,VERBAL THREAT,Adult Other,34.0567,-118.2024,SIMPLE ASSAULT,1,61-Above,2015
10,2015-07-08,22:00:00,Rampart,INTIMATE PARTNER - SIMPLE ASSAULT,31,F,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0891,-118.2992,SIMPLE ASSAULT,1,26-35,2015
13,2015-03-30,04:30:00,Southeast,INTIMATE PARTNER - AGGRAVATED ASSAULT,26,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.9479,-118.2869,AGG. ASSAULTS,1,26-35,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902215,2019-11-20,18:50:00,Southwest,BATTERY - SIMPLE ASSAULT,27,M,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0196,-118.3237,SIMPLE ASSAULT,1,26-35,2019
902216,2019-01-20,20:00:00,Southeast,CRIMINAL THREATS - NO WEAPON DISPLAYED,18,F,Black,VERBAL THREAT,Invest Cont,33.9348,-118.2500,SIMPLE ASSAULT,2,13-18,2019
902217,2019-02-23,22:20:00,Van Nuys,ROBBERY,30,F,White,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,26-35,2019
902218,2019-02-22,08:40:00,Harbor,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,White,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,13-18,2019
902220,2019-01-06,21:00:00,Olympic,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,45-60,2019

In [18]:
df.shape[0]

356584

In [19]:
df['crm_cat'].unique()

array(['AGG. ASSAULTS', 'ROBBERY', 'SIMPLE ASSAULT', 'RAPE',
       'SEX OFFENSES', 'BURGLARY', 'VANDALISM', 'OTHER THEFT',
       'OTHER CRIMES', 'BTFV', 'OFFENSES AGAINST THE FAMILY AND CHILDREN',
       'HOMICIDE', 'PERSONAL THEFT', 'FORGERY AND COUNTERFEITING',
       'ARSON', 'MVT', 'HUMAN TRAFFICKING', 'FRAUD', 'EMBEZZLEMENT'],
      dtype=object)

In [20]:
df.groupby('crm_cat').sum()['total_crm'].index

Index(['AGG. ASSAULTS', 'ARSON', 'BTFV', 'BURGLARY', 'EMBEZZLEMENT',
       'FORGERY AND COUNTERFEITING', 'FRAUD', 'HOMICIDE', 'HUMAN TRAFFICKING',
       'MVT', 'OFFENSES AGAINST THE FAMILY AND CHILDREN', 'OTHER CRIMES',
       'OTHER THEFT', 'PERSONAL THEFT', 'RAPE', 'ROBBERY', 'SEX OFFENSES',
       'SIMPLE ASSAULT', 'VANDALISM'],
      dtype='object', name='crm_cat')

In [21]:
df.to_csv('laC.csv', index=False)

In [22]:
df['year'].min()

2015

In [24]:
df['year'].max()

2019

In [82]:
df.groupby(['year', 'AREA_NAME']).sum()

                  Vict_Age          LAT          LON  total_crm
year AREA_NAME
2015 77th Street    228813  225884.1872 -786441.7949       7060
     Central        160224  139044.9321 -482930.7874       4501
     Devonshire      70384   65999.1213 -228423.5451       2190
     Foothill        79031   77407.9873 -267555.6943       2619
     Harbor          84542   83003.4941 -290743.2830       2827
...                    ...          ...          ...        ...
2019 Topanga         84977   78205.5193 -271237.0569       2597
     Van Nuys       103993   94106.4740 -326087.1279       3108
     West LA         71072   61428.9353 -213659.5093       1994
     West Valley     88617   80039.5932 -277457.8930       2694
     Wilshire        97510   88927.5170 -309015.4998       2922

[105 rows x 4 columns]

In [78]:
df.groupby(['year', 'AREA_NAME']).sum().index[3][0]

2015

In [44]:
type(df.groupby(['year', 'AREA_NAME']).sum())

pandas.core.frame.DataFrame

In [41]:
df

,DATE_OCC,TIME_OCC,AREA_NAME,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,VAge_Grp,year
2,2015-01-21,14:15:00,Olympic,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,Hispanic/Latin/Mexican,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,26-35,2015
8,2015-07-28,10:20:00,77th Street,ROBBERY,52,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,33.9757,-118.3294,ROBBERY,1,45-60,2015
9,2015-11-03,21:00:00,Hollenbeck,CRIMINAL THREATS - NO WEAPON DISPLAYED,75,F,Hispanic/Latin/Mexican,VERBAL THREAT,Adult Other,34.0567,-118.2024,SIMPLE ASSAULT,1,61-Above,2015
10,2015-07-08,22:00:00,Rampart,INTIMATE PARTNER - SIMPLE ASSAULT,31,F,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0891,-118.2992,SIMPLE ASSAULT,1,26-35,2015
13,2015-03-30,04:30:00,Southeast,INTIMATE PARTNER - AGGRAVATED ASSAULT,26,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.9479,-118.2869,AGG. ASSAULTS,1,26-35,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902215,2019-11-20,18:50:00,Southwest,BATTERY - SIMPLE ASSAULT,27,M,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0196,-118.3237,SIMPLE ASSAULT,1,26-35,2019
902216,2019-01-20,20:00:00,Southeast,CRIMINAL THREATS - NO WEAPON DISPLAYED,18,F,Black,VERBAL THREAT,Invest Cont,33.9348,-118.2500,SIMPLE ASSAULT,2,13-18,2019
902217,2019-02-23,22:20:00,Van Nuys,ROBBERY,30,F,White,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,26-35,2019
902218,2019-02-22,08:40:00,Harbor,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,White,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,13-18,2019
902220,2019-01-06,21:00:00,Olympic,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,45-60,2019

In [42]:
df[['year', 'total_crm']]

        year  total_crm
2       2015          2
8       2015          1
9       2015          1
10      2015          1
13      2015          1
...      ...        ...
902215  2019          1
902216  2019          2
902217  2019          2
902218  2019          1
902220  2019          1

[356584 rows x 2 columns]

In [83]:
df

,DATE_OCC,TIME_OCC,AREA_NAME,Crm_Cd_Desc,Vict_Age,Vict_Sex,Vict_Descent,Weapon_Desc,Status_Desc,LAT,LON,crm_cat,total_crm,VAge_Grp,year
2,2015-01-21,14:15:00,Olympic,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",28,F,Hispanic/Latin/Mexican,HAND GUN,Invest Cont,34.0526,-118.2989,AGG. ASSAULTS,2,26-35,2015
8,2015-07-28,10:20:00,77th Street,ROBBERY,52,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,33.9757,-118.3294,ROBBERY,1,45-60,2015
9,2015-11-03,21:00:00,Hollenbeck,CRIMINAL THREATS - NO WEAPON DISPLAYED,75,F,Hispanic/Latin/Mexican,VERBAL THREAT,Adult Other,34.0567,-118.2024,SIMPLE ASSAULT,1,61-Above,2015
10,2015-07-08,22:00:00,Rampart,INTIMATE PARTNER - SIMPLE ASSAULT,31,F,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0891,-118.2992,SIMPLE ASSAULT,1,26-35,2015
13,2015-03-30,04:30:00,Southeast,INTIMATE PARTNER - AGGRAVATED ASSAULT,26,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.9479,-118.2869,AGG. ASSAULTS,1,26-35,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902215,2019-11-20,18:50:00,Southwest,BATTERY - SIMPLE ASSAULT,27,M,Hispanic/Latin/Mexican,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0196,-118.3237,SIMPLE ASSAULT,1,26-35,2019
902216,2019-01-20,20:00:00,Southeast,CRIMINAL THREATS - NO WEAPON DISPLAYED,18,F,Black,VERBAL THREAT,Invest Cont,33.9348,-118.2500,SIMPLE ASSAULT,2,13-18,2019
902217,2019-02-23,22:20:00,Van Nuys,ROBBERY,30,F,White,OTHER,Invest Cont,34.2085,-118.4553,ROBBERY,2,26-35,2019
902218,2019-02-22,08:40:00,Harbor,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,14,F,White,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,33.7257,-118.2801,OFFENSES AGAINST THE FAMILY AND CHILDREN,1,13-18,2019
902220,2019-01-06,21:00:00,Olympic,CRIMINAL THREATS - NO WEAPON DISPLAYED,46,F,Black,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,34.0637,-118.2870,SIMPLE ASSAULT,1,45-60,2019

In [97]:
df[df['Vict_Sex'] == 'F'].shape[0]

186148

In [99]:
df.shape[0]

356584

In [104]:
df.loc[:,'AREA_NAME'].unique()

array(['Olympic', '77th Street', 'Hollenbeck', 'Rampart', 'Southeast',
       'West LA', 'Topanga', 'Newton', 'Mission', 'Van Nuys', 'Hollywood',
       'Wilshire', 'Northeast', 'Harbor', 'Central', 'Devonshire',
       'Southwest', 'Pacific', 'Foothill', 'N Hollywood', 'West Valley'],
      dtype=object)